version: "3.3"
services:
  biss-server:
    container_name: biss-server
    build: .
    environment:
      JWT_SECRET: test
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - backend
  biss-nginx:
    container_name: biss-nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - biss-server
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mongo:

